### ISSUE TITLE
"TAKE ME THERE" button should be in focus when opens the link

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AnonymousRedirect#13]
At the moment needs two actions to precess - Tab and Enter.
Sample links - in any report in https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by ameshkov** [comment]
Done in https://github.com/AdguardTeam/AnonymousRedirect/commit/63d2bfa7dca6d59fc3f4ab91a42e17aca5a020c5

**Comment by Alex-302** [comment]
Thanks.
